version: '3.8'

services:
  # frontend:
  #   container_name: circuit-frontend
  #   image: circuit-frontend:latest
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=production
  #     - REACT_APP_API_URL=https://smith11.ce.kmitl.ac.th  # ให้ Frontend ใช้ URL นี้
  #   command: ["npm", "run", "preview"]
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

  backend:
    container_name: circuit-backend
    image: circuit-backend:latest
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=node_user
      - DB_PASSWORD=Admin123!
      - DB_NAME=Project_circuit
    command: ["node", "src/server.js"]
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: circuit-db
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Project_circuit
      MYSQL_USER: node_user
      MYSQL_PASSWORD: Admin123!
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
